fragment ManifestEntry on ManifestEntry {
  alias
  actionHash
  app
  key
  version
  effect
}

fragment PythonFlow on PythonFlow {
  id
  title
  description
  lineage
  source
  entrypoint
  runtime
  status
  hash
  physical
  createdAt
  previous {
    id
  }
  args {
    ...FlussArgPort
  }
  returns {
    ...FlussReturnPort
  }
  manifest {
    ...ManifestEntry
  }
}

fragment ListPythonFlow on PythonFlow {
  id
  title
  lineage
  status
  hash
  createdAt
}

fragment PythonRun on PythonRun {
  id
  taskId
  status
  createdAt
  finishedAt
  flow {
    id
    title
  }
}
